### PR TITLE
Update it.po

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Review by mariospr — COMMENTED** [review]
@albanobattistella I don't see any actual change in this PR, just some additional text in a comment and updating the revision date. Did you miss uploading something else to this PR?

**Comment by albanobattistella** [comment]
> @albanobattistella I don't see any actual change in this PR, just some additional text in a comment and updating the revision date. Did you miss uploading something else to this PR?

Hi ,

sorry for mistake! could you relaise a new version for have a Italian language? Thanks! Albano

**Comment by mariospr** [comment]
> > @albanobattistella I don't see any actual change in this PR, just some additional text in a comment and updating the revision date. Did you miss uploading something else to this PR?
> 
> Hi ,
> 
> sorry for mistake! could you relaise a new version for have a Italian language? Thanks! Albano

I don't understand... do you mean releasing a new version **without** even merging this PR?

**Comment by albanobattistella** [comment]
Hi,

yes, please, could you merge My translations? Because at the moment the italian language is not displayed. Thanks!
________________________________
Da: Mario Sanchez Prada ***@***.***>
Inviato: lunedì 22 agosto 2022 19:17
A: mariospr/text-scaler-gnome-shell-extension ***@***.***>
Cc: albanobattistella ***@***.***>; Mention ***@***.***>
Oggetto: Re: [mariospr/text-scaler-gnome-shell-extension] Update it.po (PR #9)


@albanobattistella<https://github.com/albanobattistella> I don't see any actual change in this PR, just some additional text in a comment and updating the revision date. Did you miss uploading something else to this PR?

Hi ,

sorry for mistake! could you relaise a new version for have a Italian language? Thanks! Albano

I don't understand... do you mean releasing a new version without even merging this PR?

**Comment by mariospr** [comment]
Ah, I understand now: the problem is that the italian translation was created after the latest release, so you are just asking for a new release regardless of this PR (which does nothing). I'll close this PR then and make that new release.

**Comment by mariospr** [comment]
Done: Release 9 published in https://extensions.gnome.org/extension/1018/text-scaler for 3.34 for now (I'll need more time to port it to GNOME 40 & 42, sorry), see below:

image

**Pull request closed without merging**
