### PR TITLE
Update LINGUAS

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by mariospr** [comment]
Can you please merge this change into https://github.com/mariospr/text-scaler-gnome-shell-extension/pull/10 ?

We don't need two separate PRs for changes that are logically related to the same thing (i.e. add a new language), so I'm closing this PR for now and we can continue in that other PR.

Also... are you planning to propose more languages? Don't get me wrong, I appreaciate a lot your contributions and I'm very happy to receive them, I'm just asking because I just released a new version of this extension as per your request in https://github.com/mariospr/text-scaler-gnome-shell-extension/pull/9 to make the Italian language accessible, and I want to avoid having to make another release soon for this if more languages are coming in the short term (would be better make a single release grouping them all).

Thanks!

**Comment by albanobattistella** [comment]
Hi,
yes, I planning to add more languages.
I'm trying to make a single pull request ... but it gives me two separate files.
As soon as I can I send you everything.
Thanks for the new Italian version.
Regards,
Albano
________________________________
Da: Mario Sanchez Prada ***@***.***>
Inviato: martedì 23 agosto 2022 13:24
A: mariospr/text-scaler-gnome-shell-extension ***@***.***>
Cc: albanobattistella ***@***.***>; Author ***@***.***>
Oggetto: Re: [mariospr/text-scaler-gnome-shell-extension] Update LINGUAS (PR #11)


Can you please merge this change into #10<https://github.com/mariospr/text-scaler-gnome-shell-extension/pull/10> ?

We don't need two separate PRs for changes that are logically related to the same thing (i.e. add a new language), so I'm closing this PR for now and we can continue in that other PR.

Also... are you planning to propose more languages? Don't get me wrong, I appreaciate a lot your contributions and I'm very happy to receive them, I'm just asking because I just released a new version of this extension as per your request in #9<https://github.com/mariospr/text-scaler-gnome-shell-extension/pull/9> to make the Italian language accessible, and I want to avoid having to make another release soon for this if more languages are coming in the short term (would be better make a single release grouping them all).

Thanks!

**Comment by mariospr** [comment]
> I'm trying to make a single pull request ... but it gives me two separate files.

That shouldn't be a problem, you can add multiple files to a single commit with `git add`.

If you're planning to add multiple languages then I'd said the best thing would be to have **one single PR** with several commits, one per language e.g.: one commit adding the fr.po file + the change in LINGUAS to add `fr`, then another commit adding another `.po` file + the relevant changes in `LINGUAS`... and so on so that, in the end, you get a PR with _n_ commits where _n_ is the number of new languages you're adding.

WDYT?

**Comment by albanobattistella** [comment]
> Can you please merge this change into #10 ?
> 
> We don't need two separate PRs for changes that are logically related to the same thing (i.e. add a new language), so I'm closing this PR for now and we can continue in that other PR.
> 
> Also... are you planning to propose more languages? Don't get me wrong, I appreaciate a lot your contributions and I'm very happy to receive them, I'm just asking because I just released a new version of this extension as per your request in #9 to make the Italian language accessible, and I want to avoid having to make another release soon for this if more languages are coming in the short term (would be better make a single release grouping them all).
> 
> Thanks!



> > I'm trying to make a single pull request ... but it gives me two separate files.
> 
> That shouldn't be a problem, you can add multiple files to a single commit with `git add`.
> 
> If you're planning to add multiple languages then I'd said the best thing would be to have **one single PR** with several commits, one per language e.g.: one commit adding the fr.po file + the change in LINGUAS to add `fr`, then another commit adding another `.po` file + the relevant changes in `LINGUAS`... and so on so that, in the end, you get a PR with _n_ commits where _n_ is the number of new languages you're adding.
> 
> WDYT?

Hi ,
I closed all pull request.
Now the new is 14.
Solved for other.
Thanks.

**Comment by mariospr** [comment]
> Hi , I closed all pull request. Now the new is 14. Solved for other. Thanks.

Ok, I'll wait a bit though until you confirm you're not adding more languages as part of that other PR. As I said, I don't want to be merging multiple PRs nor making multiple releases if we can avoid it.

**Pull request closed without merging**
