### PR TITLE
Added Localization Support + German

### PR DESCRIPTION
**Pull request by jonnius**

### CODE REVIEW

**Comment by mariospr** [comment]
Hey! Thanks for the patch, and sorry for the (very) late reply. I haven't seen any email notification about this and found it almost by chance which, combined with me not normally looking at github notifications on the web interface, was a recipe for disaster.

Anyway, I reviewed the PR and I'm happy to include these feature on the extension, although it would need a few changes before I can really hit the merge button:
- The `convenience.js` file you're adding is basically an stripped-down version of the original one at https://github.com/gcampax/gnome-shell-extensions/blob/master/lib/convenience.js, without the license header, so I can't really merge it as it is. Please import the original file from @gcampax, even if we don't use the second utility function (`getSettings()`). I'd rather have it like that.
- About the `.po` file, the right place to include in the source tree would be inside a `po/` directory, not in `locale/de/LC_MESSAGES/`, together with a `POTFILES.in` and a `LINGUAS` file. You'll need to add some bits in the `Makefile` to make it work (perhaps easier using autotools), but that's how it should be done. Take a look to https://github.com/gcampax/gnome-shell-extensions.
- Last, no need to include generated files: please remove the `.pot` and the `.mo` files from this PR

Let me know if you have any doubt, though.

Again, thanks a lot for your contribution, and sorry again for the huge delay getting back to it!

**Comment by jonnius** [comment]
Thanks for you advice! I've already updated the commit. The only thing I don't know how to do is editing the Makefile. I guess you want me to add lines so that de po files are being updated automatically from the source? I didn't find those lines in gcampax' Makefile and don't know how to achieve that.

**Comment by mariospr** [comment]
No problem, I can do that myself later on. But for now, this is already good to me as a first step, so I just merged your pull request as it is. I'll try to do the missing bits before soon.

Thanks a lot for your patch! (and for reminding me I wanted to translate this right from the start)

**Comment by mariospr** [comment]
It was about time, but the autotools integration is ready and pushed: https://github.com/mariospr/text-scaler-gnome-shell-extension/commit/6a72a0be9254729b4004314ac0735b53de989ce0.

I've tested this myself in a VM setting the language to German and seems to work fine, so I'm releasing version 3 of the extension now as welll, along with a minor update to declare GNOME Shell 3.20 as supported, too: https://github.com/mariospr/text-scaler-gnome-shell-extension/commit/6707ac4d8a7e9e67d316fce1fc492e79b4fe9023

Expect the updated version soon in extensions.gnome.org, fully translated to German. Thanks again!

**Pull request merged**
